from django.urls import path
from rest_framework.authtoken import views
from .views import (
    UserView,
    NoteView,
    NoteDetailView,
    NoteFileView,
    NoteFileDetailView,
    UniversityView,
    UniversityDetailView,
    RatingView,
    RatingDetailView,
    SelfView,
    SelfNoteView,
    SelfGroupView,
    SelfInvitationView,
    SelfFavoritesView,
    CommentView,
    CommentDetailView,
    GroupView,
    GroupDetailView,
    GroupNoteView,
    GroupMembershipView,
    GroupMembershipDetailView,
    GroupInvitationView,
    GroupInvitationDetailView,
    FavoriteView,
    FavoriteDetailView,
)

urlpatterns = [
    path("login/", views.obtain_auth_token),
    path("user/", SelfView.as_view()),
    path("user/notes/", SelfNoteView.as_view()),
    path("user/groups/", SelfGroupView.as_view()),
    path("user/invitations/", SelfInvitationView.as_view()),
    path("user/favorites/", SelfFavoritesView.as_view()),
    path("users/", UserView.as_view()),
    path("notes/", NoteView.as_view()),
    path("notes/<int:pk>/", NoteDetailView.as_view()),
    path("notes/<int:note_id>/files/", NoteFileView.as_view()),
    path("notes/<int:note_id>/files/<int:index>", NoteFileDetailView.as_view()),
    path("notes/<int:note_id>/ratings/", RatingView.as_view()),
    path("notes/<int:note_id>/ratings/<int:pk>", RatingDetailView.as_view()),
    path("notes/<int:note_id>/comments/", CommentView.as_view()),
    path("notes/<int:note_id>/comments/<int:pk>/", CommentDetailView.as_view()),
    path("notes/<int:note_id>/favorites/", FavoriteView.as_view()),
    path("notes/<int:note_id>/favorites/<int:pk>/", FavoriteDetailView.as_view()),
    path("universities/", UniversityView.as_view()),
    path("universities/<str:name>/", UniversityDetailView.as_view()),
    path("groups/", GroupView.as_view()),
    path("groups/<int:pk>/", GroupDetailView.as_view()),
    path("groups/<int:group_id>/notes/", GroupNoteView.as_view()),
    path("groups/<int:group_id>/memberships/", GroupMembershipView.as_view()),
    path(
        "groups/<int:group_id>/memberships/<int:pk>/",
        GroupMembershipDetailView.as_view(),
    ),
    path("groups/<int:group_id>/invitations/", GroupInvitationView.as_view()),
    path(
        "groups/<int:group_id>/invitations/<int:pk>/",
        GroupInvitationDetailView.as_view(),
    ),
]
